wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-first.sh
source setup-first.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-lamp.sh
source setup-lamp.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-ruby.sh
source setup-ruby.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-perl.sh
source setup-perl.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-python.sh
source setup-python.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-node.sh
source setup-node.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-japanese.sh
source setup-japanese.sh
wget https://raw.githubusercontent.com/ht0919/setup-ubuntu/master/setup-emacs.sh
source setup-emacs.sh
